// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tech2Gether_api.Data;

#nullable disable

namespace Tech2Gether_api.Migrations
{
    [DbContext(typeof(T2TContext))]
    partial class T2TContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tech2Gether_api.Data.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("street_1");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("street_2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("zip");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_address_user_id");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int")
                        .HasColumnName("meeting_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AttendanceId");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("idx_attendance_meeting_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_attendance_user_id");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_date");

                    b.Property<DateTime?>("EventEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_end_date");

                    b.Property<int?>("EventSourceId")
                        .HasColumnType("int")
                        .HasColumnName("event_source_id");

                    b.HasKey("EventId");

                    b.HasIndex("EventSourceId")
                        .HasDatabaseName("idx_event_source_id");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventDef", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("EventTypeDesc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("event_type_desc");

                    b.HasKey("EventTypeId");

                    b.ToTable("event_def", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventSource", b =>
                {
                    b.Property<int>("EventSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_source_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventSourceId"));

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("event_name");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int")
                        .HasColumnName("event_type_id");

                    b.HasKey("EventSourceId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("event_source", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("team_name");

                    b.Property<int?>("UserTeamId")
                        .HasColumnType("int")
                        .HasColumnName("user_team_id");

                    b.HasKey("TeamId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserTeamId");

                    b.ToTable("event_team", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Login", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<bool>("EmailIsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_is_verified");

                    b.Property<DateTime?>("EmailVerificationExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("email_verification_expires");

                    b.Property<string>("EmailVerificationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email_verification_token");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("password_reset_expires");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password_reset_token");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("meeting_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<DateTime?>("MeetingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("meeting_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("MeetingId");

                    b.ToTable("meeting", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.MembershipDef", b =>
                {
                    b.Property<int>("MemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mem_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemId"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("MemDesc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mem_desc");

                    b.HasKey("MemId");

                    b.ToTable("membership_def", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Organization", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrgId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("OrgEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("org_email");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("org_name");

                    b.Property<string>("OrgPhone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("org_phone");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("OrgId");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("idx_organization_address_id");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Speaker", b =>
                {
                    b.Property<int>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("speaker_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpeakerId"));

                    b.Property<string>("SpeakerFirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("speaker_first_name");

                    b.Property<string>("SpeakerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("speaker_last_name");

                    b.Property<string>("SpeakerLinkedin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("speaker_linkedin");

                    b.Property<int?>("SpeakerOrganization")
                        .HasColumnType("int")
                        .HasColumnName("speaker_organization");

                    b.Property<string>("SpeakerTitle")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("speaker_title");

                    b.HasKey("SpeakerId");

                    b.HasIndex("SpeakerOrganization");

                    b.ToTable("speaker", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.SpeakerMeeting", b =>
                {
                    b.Property<int>("SpeakerMeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("speaker_meeting_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpeakerMeetingId"));

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int")
                        .HasColumnName("meeting_id");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("int")
                        .HasColumnName("speaker_id");

                    b.HasKey("SpeakerMeetingId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("speaker_meeting", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmFirstName")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("em_first_name");

                    b.Property<string>("EmLastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("em_last_name");

                    b.Property<string>("EmPhone")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("em_phone");

                    b.Property<string>("EmRelationship")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("em_relationship");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<int?>("MemId")
                        .HasColumnType("int")
                        .HasColumnName("mem_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("phone");

                    b.Property<string>("PreName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("pre_name");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("pronouns");

                    b.Property<string>("UserGithub")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("user_github");

                    b.Property<string>("UserLinkedin")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("user_linkedin");

                    b.HasKey("UserId");

                    b.HasIndex("MemId")
                        .HasDatabaseName("idx_user_mem_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.UserOrg", b =>
                {
                    b.Property<int>("UserOrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_org_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserOrgId"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<DateTime?>("GraduationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("graduation_date");

                    b.Property<int?>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserOrgId");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("idx_user_org_org_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_org_user_id");

                    b.ToTable("user_org", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.UserTeam", b =>
                {
                    b.Property<int>("UserTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_team_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserTeamId"));

                    b.Property<bool>("Leader")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("leader");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserTeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("user_team", (string)null);
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Address", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Attendance", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.Meeting", "Meeting")
                        .WithMany("Attendances")
                        .HasForeignKey("MeetingId");

                    b.HasOne("Tech2Gether_api.Data.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId");

                    b.Navigation("Meeting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Event", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.EventSource", "EventSource")
                        .WithMany("Events")
                        .HasForeignKey("EventSourceId");

                    b.Navigation("EventSource");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventSource", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.EventDef", "EventDef")
                        .WithMany("EventSources")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDef");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventTeam", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.Event", "Event")
                        .WithMany("EventTeams")
                        .HasForeignKey("EventId");

                    b.HasOne("Tech2Gether_api.Data.UserTeam", "UserTeam")
                        .WithMany()
                        .HasForeignKey("UserTeamId");

                    b.Navigation("Event");

                    b.Navigation("UserTeam");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Login", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.User", "User")
                        .WithOne("Login")
                        .HasForeignKey("Tech2Gether_api.Data.Login", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Organization", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Speaker", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("SpeakerOrganization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.SpeakerMeeting", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.Meeting", "Meeting")
                        .WithMany("SpeakerMeetings")
                        .HasForeignKey("MeetingId");

                    b.HasOne("Tech2Gether_api.Data.Speaker", "Speaker")
                        .WithMany("SpeakerMeetings")
                        .HasForeignKey("SpeakerId");

                    b.Navigation("Meeting");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.User", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.MembershipDef", "MembershipDef")
                        .WithMany("Users")
                        .HasForeignKey("MemId");

                    b.Navigation("MembershipDef");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.UserOrg", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.Organization", "Organization")
                        .WithMany("UserOrgs")
                        .HasForeignKey("OrgId");

                    b.HasOne("Tech2Gether_api.Data.User", "User")
                        .WithMany("UserOrgs")
                        .HasForeignKey("UserId");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.UserTeam", b =>
                {
                    b.HasOne("Tech2Gether_api.Data.EventTeam", "EventTeam")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId");

                    b.HasOne("Tech2Gether_api.Data.User", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId");

                    b.Navigation("EventTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Event", b =>
                {
                    b.Navigation("EventTeams");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventDef", b =>
                {
                    b.Navigation("EventSources");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventSource", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.EventTeam", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Meeting", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("SpeakerMeetings");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.MembershipDef", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Organization", b =>
                {
                    b.Navigation("UserOrgs");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.Speaker", b =>
                {
                    b.Navigation("SpeakerMeetings");
                });

            modelBuilder.Entity("Tech2Gether_api.Data.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Attendances");

                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("UserOrgs");

                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
