<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Folder Include="Views\Components\" />
	</ItemGroup>

	<Target Name="BuildTailwind" BeforeTargets="Build">
		<Exec Command="npm run build" />
	</Target>

</Project>
